title: [DHP D258]
logo: figures/network.png
description: [Gathering, visualizing and modeling data in context for diplomacy and global affairs.]
theme: just-the-docs

url: https://annahaensch.github.io/

plugins:
  - jekyll-default-layout

